### ISSUE TITLE
Error at updating

### ISSUE THREAD

**Issue by icebob** [Eomm/notion-board#17]
Hi,

I've just tried your Action, but I've got an error message and don't know what the problem is. Could you check it plz?
![image](https://user-images.githubusercontent.com/306521/217050862-03327d89-a00b-4421-aa6e-07aed1baa76d.png)

My workflow: https://github.com/moleculerjs/site/blob/master/.github/workflows/notion.yml
Action run: https://github.com/moleculerjs/site/actions/runs/4106547562/jobs/7084916859
Notion template:
![image](https://user-images.githubusercontent.com/306521/217050570-302fc9c5-c453-4ca8-a191-18323fdaf1d9.png)

Thanks in advance.

**Comment by icebob** [comment]
I can't select rich-text field type for topics:
![image](https://user-images.githubusercontent.com/306521/217051205-61687f93-6ea5-4b44-b8ca-70ef425271a4.png)

**Comment by icebob** [comment]
Nevermind, I set wrong type for "Topics", now it works

**Comment by Eomm** [comment]
Thanks for sharing - I know that the onboarding is a bit odd right now.

I'm checking how to create the database automatically and without bounding to the columns' name

**Comment by icebob** [comment]
yeah, it would be cool feature because I've never created database on Notion to it was a little tricky for me :)
