### ISSUE TITLE
Supporting NPM scopes?

### ISSUE THREAD

**Issue by icebob** [Eomm/notion-board#18]
As a feature request, can you support NPM scopes? I have many NPM libraries under the `@moleculer/....` scope. The current Action script can't monitor them.

**Comment by Eomm** [comment]
Thanks for reporting, totally agree

I was building the fastify dashboard
https://eomm.notion.site/7a064537ee794af698684df68e215b54?v=a660ff01ca5344769a5f2b1a1c4eeda4
and I noticed it - I'm checking how to define the best relation between:

- github
- the npm package
- the notion database row

**Comment by icebob** [comment]
It was quick and working fine, thanks, keep up the good work!
